### ISSUE TITLE
起動時にクラッシュ

### ISSUE THREAD

**Issue by kawaemon** [ReiRokusanami0010/TinkersGunsConstruction#3]
クラッシュレポート
```
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:596)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:249)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.init(Minecraft.java:535)
	at net.minecraft.client.Minecraft.run(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)
```
ログ
[latest.log](https://github.com/ReiRokusanami0010/TinkersGunsConstruction/files/3266099/latest.log)
[debug.log](https://github.com/ReiRokusanami0010/TinkersGunsConstruction/files/3266134/debug.log)

既知の問題ですが、一応。

**Comment by kawaemon** [comment]
fixed 69c49c7b32e8915f9528e5f8baf9ec39c520911f
